### ISSUE TITLE
ttfautohint.options.parse_args() mishandles Windows paths

### ISSUE THREAD

**Issue by madig** [fonttools/ttfautohint-py#2]
```
import ttfautohint
ttfautohint.options.parse_args('-n -l 8 -r 50 -G 50 -x 14 -D latn -f latn -a qsq build\\unhinted\\Test_Lt.ttf build\\hinted\\Test_Lt.ttf')
```
Got: `{'in_file': 'buildunhintedTest_Lt.ttf', 'out_file': 'buildhintedTest_Lt.ttf, ...'`
Expected: `{'in_file': 'build\\unhinted\\Test_Lt.ttf', 'out_file': 'build\\hinted\\Test_Lt.ttf', ...`

**Comment by anthrotype** [comment]
Thanks for the report. It looks like `shlex.split` is responsible for this. Passing the argument `posix=False` to shlex.split (perhaps based on the value of sys.platform) can fix this particular problem with backslashes, but I'm not sure if it could introduce other unwanted issues.
I'll see what I can do.

**Comment by anthrotype** [comment]
related https://bugs.python.org/issue1724822

**Comment by anthrotype** [comment]
apparently, shlex is meant to be an implementation of Unix shell behavior, and is *not supposed* to handle Windows command lines.

in the Jython source code, there's a `_cmdline2list` function that implements the MSVC command line rules:
https://bitbucket.org/jython/jython/src/d74f8c2cd56f24c7af8b1aab36433f941d0a44e9/Lib/subprocess.py?at=default&fileviewer=file-view-default#subprocess.py-667 

maybe we could borrow that here.

**Comment by anthrotype** [comment]
updated link to Jython's source code (the one above doesn't work anymore) for the `_cmdline2list` method:
https://github.com/jython/jython/blob/50729e600faa99454a5c652fde285f3830611126/Lib/subprocess.py#L668-L722
