### ISSUE TITLE
Can this be used in the shell?

### ISSUE THREAD

**Issue by arrowtype** [fonttools/ttfautohint-py#20]
Sorry if this is a stupid question, but can this be used on the shell?

My expectation was that I could pip install this, and then the command `ttfautohint` would work. I don’t see any such command in `venv/bin`, however, and just trying it out results in `command not found: ttfautohint`.

For now, I’ll make a Python script to run this, and call that from the shell, but is there a simpler way?

Thanks!

**Comment by arrowtype** [comment]
Ah, nevermind – it can be used like this:

```bash
python3 -m ttfautohint [in-font] [out-font]
```

**Comment by anthrotype** [comment]
Correct
We did that to avoid shadowing an existing ttfautohint binary, and make it explicit that one is calling ttfautohint via python
