### ISSUE TITLE
Harfbuzz build: --disable-gtk-doc-html unrecognized

### ISSUE THREAD

**Issue by madig** [fonttools/ttfautohint-py#4]
According to the Appveyor log (https://ci.appveyor.com/project/fonttools/ttfautohint-py/build/job/a75dl5ce4w8hpeho), Harfbuzz' configure doesn't recognize `--disable-gtk-doc-html`. Documentation is not built because some gtk-doc thing isn't found. 

Not a real issue I guess but wanted to point out anyway. I think you have to use `--enable-gtk-doc-html=no` instead.

**Comment by behdad** [comment]
Probably because gtk-doc was not available during autogen.sh, so configure doesn't know about the option either.
