### ISSUE TITLE
pip install fails on Linux: No matching distribution found for ttfautohint-py

### ISSUE THREAD

**Issue by graphicore** [fonttools/ttfautohint-py#5]
I'm not sure why it doesn't install.

```
$ python --version
Python 3.7.3
$ pip search ttfautohint
ttfautohint-py (0.4.3)  - Python wrapper for ttfautohint, a free auto-hinter for TrueType fonts
font-ttfa (0.9.1)       - A command line TTFA table reporting tool for fonts hinted with ttfautohint
$ pip install ttfautohint-py
ERROR: Could not find a version that satisfies the requirement ttfautohint-py (from versions: none)
ERROR: No matching distribution found for ttfautohint-py
```

**Comment by graphicore** [comment]
I was able to build from source using:

```
$ pip install git+https://github.com/fonttools/ttfautohint-py.git@v0.4.3#egg=ttfautohint-py
```

Had to provide some build dependencies.

**Comment by anthrotype** [comment]
that's strange. We build "manylinux" wheels that are supposed to work on any linux distro. Maybe the `pip --version` that you are using to install it is obsolete. Please try to `pip install --upgrade pip` and see if that works

**Comment by chrissimpkins** [comment]
Cosimo, does `python setup.py build_ext` build this project's compiled submodules?  And I should be able pip install the ttfautohint package for testing with `pip install -e .` thereafter?

**Comment by eliheuer** [comment]
I just got the same error on macOS 11.2.

**Comment by anthrotype** [comment]
> I just got the same error on macOS 11.2

what python version?
have you got one of the apple silicon macbooks?

**Comment by eliheuer** [comment]
Python 3.9.1
Mac mini (M1, 2020) -- apple silicon

Edit: I updated to Python 3.9.2 using `brew` but still get:
```
$ pip install ttfautohint-py
ERROR: Could not find a version that satisfies the requirement ttfautohint-py
ERROR: No matching distribution found for ttfautohint-py
```
