### ISSUE TITLE
No wheels for macOS 12 M1

### ISSUE THREAD

**Issue by simoncozens** [fonttools/ttfautohint-py#9]
Existing wheel on pypi doesn't want to install on a new M1 / 12.0 / Python 3.8.9:

```
ERROR: ttfautohint_py-0.4.3.post1-py2.py3-none-macosx_10_9_universal2.whl is not a supported wheel on this platform.
```

Further compounded by the fact that trying to build freetype on M1/12.0 fails with this lovely error message:

```
/Users/simon/ttfautohint-py/src/c/freetype2/builds/unix/configure  '--without-bzip2' '--without-png' '--without-zlib' '--without-harfbuzz' '--prefix=/Users/simon/ttfautohint-py/build/local' '--enable-static' '--disable-shared' '--enable-freetype-config' 'PKG_CONFIG= ' 'CFLAGS=-I/Users/simon/ttfautohint-py/build/local/include -g -O2 -fPIC -m64 -arch x86_64 -arch arm64 -mmacosx-version-min=10.9' 'CXXFLAGS=-I/Users/simon/ttfautohint-py/build/local/include -g -O2 -fPIC -m64 -arch x86_64 -arch arm64 -mmacosx-version-min=10.9' 'LDFLAGS=-fPIC -L/Users/simon/ttfautohint-py/build/local/lib -L/Users/simon/ttfautohint-py/build/local/lib64 -m64 -arch x86_64 -arch arm64 -mmacosx-version-min=10.9'
checking build system type... Invalid configuration `arm64-apple-darwin21.1.0': machine `arm64-apple' not recognized
```

It must be something to do with autogen.sh, because the released version of freetype 2.11.0 builds fine.

macOS 12 runners not available on GitHub yet so we will need manual builds for this.

**Comment by simoncozens** [comment]
It's just the `config.sub` file from freetype release which is updated to support macOS 12/ARM. This updated `config.sub` is also needed in `src/c/ttfautohint/.gnulib/build-aux`.

**Comment by simoncozens** [comment]
With those two updated files, it builds. But...

```
$ pip3 install dist/ttfautohint_py-0.4.3.post2.dev0+g996aeea.d20211124-py2.py3-none-macosx_10_14_arm64.whl
Defaulting to user installation because normal site-packages is not writeable
ERROR: ttfautohint_py-0.4.3.post2.dev0+g996aeea.d20211124-py2.py3-none-macosx_10_14_arm64.whl is not a supported wheel on this platform.
```

WHAT?

**Comment by simoncozens** [comment]
Oh I'm a dummy. `pip3 install -U pip wheel` before doing anything. Then it works.

**Comment by khaledhosny** [comment]
You can build wheels for M1 on GitHub Actions, we do this in uharfbuzz.

**Comment by khaledhosny** [comment]
You can build wheels for M1 on GitHub Actions, we do this in uharfbuzz.

**Comment by simoncozens** [comment]
Yeah, ttfautohint already does. I just couldn't install them because of my version of pip...
